steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      pip install --upgrade pip
      pip install databricks-cli>=0.205 databricks-sdk
    displayName: Install New Databricks CLI

  - script: |
      mkdir -p ~/.databricks
      echo "[default]" > ~/.databricks/config
      echo "host = $(DATABRICKS_HOST)" >> ~/.databricks/config
      echo "token = $(DATABRICKS_TOKEN)" >> ~/.databricks/config

      databricks bundle validate -t dev
      databricks bundle deploy -t dev
    displayName: Validate & Deploy DAB Jobs
